<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Licensing - IP System</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="licensing.css">
</head>

<body>
    <div class="container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <h2 class="logo">IP System</h2>

            <ul class="menu">
                <li><a href="../dashboard/dashboard.php"><i class="fas fa-home"></i> Dashboard</a></li>
                <li><a href="../inventors/inventors.php"><i class="fas fa-user-astronaut"></i> Inventors</a></li>
                <li><a href="../invention_disclosure/disclosure.php"><i class="fas fa-lightbulb"></i> Disclosure</a>
                </li>
                <li><a href="../patent/patent.php"><i class="fas fa-file"></i> Patents</a></li>
                <li><a href="../renewals/renewals.php"><i class="fas fa-sync"></i> Renewals</a></li>
                <li><a href="./licensing.php" class="active"><i class="fas fa-handshake"></i> Licensing</a></li>
            </ul>


            <a href="../index.php" class="logout_btn">
                <button class="logout">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </button></a>
        </aside>

        <!-- Main Content -->
        <main class="page_structure">
            <!-- Navbar -->
            <nav class="panel-header">
                <div class="left">
                    <i class="fas fa-list icon-btn" onclick="toggleSidebar()"></i>
                    <h6>Licensing Management</h6>
                </div>

                <div class="right">
                    <button class="btn-primary" id="add-license-btn">
                        <i class="fas fa-plus"></i> New License
                    </button>
                </div>
            </nav>

            <!-- Content -->
            <div class="content-wrapper">
                <!-- Summary Cards -->
                <div class="summary-cards">
                    <div class="card">
                        <div class="card-icon"><i class="fas fa-file-alt"></i></div>
                        <div class="card-info">
                            <h4>Total Licenses</h4>
                            <p id="total-licenses-count">0</p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-icon"><i class="fas fa-check-circle"></i></div>
                        <div class="card-info">
                            <h4>Active</h4>
                            <p id="active-licenses-count">0</p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-icon"><i class="fas fa-hourglass-half"></i></div>
                        <div class="card-info">
                            <h4>Expiring Soon</h4>
                            <p id="expiring-licenses-count">0</p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-icon"><i class="fas fa-dollar-sign"></i></div>
                        <div class="card-info">
                            <h4>Revenue</h4>
                            <p id="total-revenue">$0</p>
                        </div>
                    </div>
                </div>

                <div class="header-actions">
                    <h2>All Licenses</h2>
                </div>

                <!-- Table -->
                <div id="licensing-table" class="table-container">
                    <!-- Table generated by JS -->
                </div>

                <!-- Alerts Section -->
                <div class="alerts-container" id="alerts-section">
                    <h3>Alerts</h3>
                    <div id="alerts-list">
                        <!-- Alerts will be injected here by JS -->
                    </div>
                </div>
            </div>
        </main>
    </div>

    <!-- Modal for adding a new license -->
    <div id="add-license-modal" class="modal-overlay">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Add New License</h2>
                <i class="fas fa-times close-modal"></i>
            </div>
            <div class="modal-body">
                <form id="add-license-form">
                    <div class="form-group">
                        <label for="license-patent">Patent</label>
                        <input type="text" id="license-patent" placeholder="e.g., US12345B2" required>
                    </div>
                    <div class="form-group">
                        <label for="license-company">Company</label>
                        <input type="text" id="license-company" placeholder="e.g., Samsung">
                    </div>
                    <div class="form-group">
                        <label for="license-type">Type</label>
                        <select id="license-type">
                            <option value="" disabled selected>Select type</option>
                            <option value="Exclusive">Exclusive</option>
                            <option value="Non-Exclusive">Non-Exclusive</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="license-territory">Territory</label>
                        <input type="text" id="license-territory" placeholder="e.g., USA, Global">
                    </div>
                    <div class="form-group">
                        <label for="license-revenue-model">Revenue Model</label>
                        <select id="license-revenue-model" required>
                            <option value="" disabled selected>Select revenue model</option>
                            <option value="Fixed">Fixed</option>
                            <option value="Per Unit">Per Unit</option>
                            <option value="Percentage">Net Sales %</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="license-revenue-value">Rate / Value</label>
                        <input type="text" id="license-revenue-value" placeholder="e.g., 5 or 10000" required>
                    </div>
                    <div class="form-group net-sales-group hidden">
                        <label for="license-net-sales">Net Sales (for Net Sales %)</label>
                        <input type="number" step="0.01" id="license-net-sales" placeholder="e.g., 500000">
                        <small class="helper-text">Leave blank to use a sample sales estimate for calculation.</small>
                    </div>
                    <div class="form-group units-sold-group hidden">
                        <label for="license-units-sold">Units Sold (for Per Unit)</label>
                        <input type="number" id="license-units-sold" placeholder="e.g., 2000">
                        <small class="helper-text">Leave blank to use a sample quantity estimate.</small>
                    </div>
                    <div class="form-group">
                        <label for="license-min-net-sales-clause">Min Net Sales Clause (optional)</label>
                        <input type="number" step="0.01" id="license-min-net-sales-clause" placeholder="e.g., 100000">
                    </div>
                    <div class="form-group">
                        <label for="license-end-date">End Date</label>
                        <input type="date" id="license-end-date">
                    </div>
                    <div class="form-actions">
                        <button type="button" class="btn-secondary close-modal">Cancel</button>
                        <button type="submit" class="btn-primary">Save License</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Modal for editing a license -->
    <div id="edit-license-modal" class="modal-overlay">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Edit License</h2>
                <i class="fas fa-times close-modal"></i>
            </div>
            <div class="modal-body">
                <form id="edit-license-form">
                    <input type="hidden" id="edit-license-id">
                    <div class="form-group">
                        <label for="edit-license-patent">Patent</label>
                        <input type="text" id="edit-license-patent" required>
                    </div>
                    <div class="form-group">
                        <label for="edit-license-company">Company</label>
                        <input type="text" id="edit-license-company">
                    </div>
                    <div class="form-group">
                        <label for="edit-license-type">Type</label>
                        <select id="edit-license-type">
                            <option value="Exclusive">Exclusive</option>
                            <option value="Non-Exclusive">Non-Exclusive</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="edit-license-status">Status</label>
                        <select id="edit-license-status" required>
                            <option value="Active">Active</option>
                            <option value="Expired">Expired</option>
                            <option value="Terminated">Terminated</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="edit-license-territory">Territory</label>
                        <input type="text" id="edit-license-territory">
                    </div>
                    <div class="form-group">
                        <label for="edit-license-revenue-model">Revenue Model</label>
                        <select id="edit-license-revenue-model" required>
                            <option value="Fixed">Fixed</option>
                            <option value="Per Unit">Per Unit</option>
                            <option value="Percentage">Net Sales %</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="edit-license-revenue-value">Rate / Value</label>
                        <input type="text" id="edit-license-revenue-value" required>
                    </div>
                    <div class="form-group net-sales-group hidden">
                        <label for="edit-license-net-sales">Net Sales (for Net Sales %)</label>
                        <input type="number" step="0.01" id="edit-license-net-sales">
                        <small class="helper-text">Leave blank to use a sample sales estimate for calculation.</small>
                    </div>
                    <div class="form-group units-sold-group hidden">
                        <label for="edit-license-units-sold">Units Sold (for Per Unit)</label>
                        <input type="number" id="edit-license-units-sold">
                        <small class="helper-text">Leave blank to use a sample quantity estimate.</small>
                    </div>
                    <div class="form-group">
                        <label for="edit-license-min-net-sales-clause">Min Net Sales Clause (optional)</label>
                        <input type="number" step="0.01" id="edit-license-min-net-sales-clause">
                    </div>
                    <div class="form-group">
                        <label for="edit-license-end-date">End Date</label>
                        <input type="date" id="edit-license-end-date">
                    </div>
                    <div class="form-actions">
                        <button type="button" class="btn-secondary close-modal">Cancel</button>
                        <button type="submit" class="btn-primary">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Modal for viewing a license -->
    <div id="view-license-modal" class="modal-overlay">
        <div class="modal-content">
            <div class="modal-header">
                <h2>License Details</h2>
                <i class="fas fa-times close-modal"></i>
            </div>
            <div class="modal-body" id="view-license-details">
                <!-- Details will be injected here by JS -->
            </div>
            <div class="form-actions" style="padding: 20px; justify-content: flex-end;">
                <button type="button" class="btn-secondary close-modal">Close</button>
            </div>
        </div>
    </div>

    <script src="licensing.js"></script>
</body>

</html>