<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventions - IP System</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="inventors.css">
</head>

<body>
    <div class="container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <h2 class="logo">IP System</h2>

            <ul class="menu">
                <li><a href="../dashboard/dashboard.php" class="active"><i class="fas fa-home"></i> Dashboard</a></li>
                <li><a href="./inventors.php"><i class="fas fa-user-astronaut"></i> Inventors</a></li>
                <li><a href="../invention_disclosure/disclosure.php"><i class="fas fa-lightbulb"></i> Disclosure</a>
                </li>
                <li><a href="#"><i class="fas fa-file"></i> Patents</a></li>
                <li><a href="#"><i class="fas fa-sync"></i> Renewals</a></li>
                <li><a href="#"><i class="fas fa-handshake"></i> Licensing</a></li>
                <li><a href="#"><i class="fas fa-chart-bar"></i> Reports</a></li>
            </ul>

            <a href=""></a </aside>

            <!-- Main Content -->
            <main class="page_structure">
                <!-- Navbar -->
                <nav class="panel-header">
                    <div class="left">
                        <i class="fas fa-list icon-btn" onclick="toggleSidebar()"></i>
                        <h6>Inventions</h6>
                    </div>

                    <div class="right">
                        <button class="btn-primary">
                            <i class="fas fa-plus"></i> New Invention
                        </button>
                    </div>
                </nav>

                <!-- Content -->
                <div class="content-wrapper">
                    <div class="header-actions">
                        <h2>My Inventions</h2>
                    </div>

                    <!-- Table will be injected here by JavaScript -->
                    <div id="inventions-table" class="table-container">
                        <!-- Table generated by JS -->
                    </div>
                </div>
            </main>
    </div>

    <!-- Modal for adding a new invention -->
    <div id="add-invention-modal" class="modal-overlay">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Add New Invention</h2>
                <i class="fas fa-times close-modal"></i>
            </div>
            <div class="modal-body">
                <form id="add-invention-form">
                    <div class="form-group">
                        <label for="inv-title">Title</label>
                        <input type="text" id="inv-title" required>
                    </div>
                    <div class="form-group">
                        <label for="inv-status">Status</label>
                        <select id="inv-status">
                            <option value="Draft">Draft</option>
                            <option value="Submitted">Submitted</option>
                            <option value="Finalized">Finalized</option>
                            <option value="Granted">Granted</option>
                            <option value="Abandoned">Abandoned</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="inv-inventors">Inventors</label>
                        <input type="text" id="inv-inventors" placeholder="e.g., John Doe, Jane Smith" required>
                    </div>
                    <div class="form-group">
                        <label for="inv-field">Field</label>
                        <input type="text" id="inv-field" required>
                    </div>
                    <div class="form-actions">
                        <button type="button" class="btn-secondary close-modal">Cancel</button>
                        <button type="submit" class="btn-primary">Save Invention</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Modal for editing an invention -->
    <div id="edit-invention-modal" class="modal-overlay">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Edit Invention</h2>
                <i class="fas fa-times close-modal"></i>
            </div>
            <div class="modal-body">
                <form id="edit-invention-form">
                    <input type="hidden" id="edit-inv-id">
                    <div class="form-group">
                        <label for="edit-inv-title">Title</label>
                        <input type="text" id="edit-inv-title" required>
                    </div>
                    <div class="form-group">
                        <label for="edit-inv-status">Status</label>
                        <select id="edit-inv-status">
                            <option value="Draft">Draft</option>
                            <option value="Submitted">Submitted</option>
                            <option value="Finalized">Finalized</option>
                            <option value="Granted">Granted</option>
                            <option value="Abandoned">Abandoned</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="edit-inv-inventors">Inventors</label>
                        <input type="text" id="edit-inv-inventors" required>
                    </div>
                    <div class="form-group">
                        <label for="edit-inv-field">Field</label>
                        <input type="text" id="edit-inv-field" required>
                    </div>
                    <div class="form-actions">
                        <button type="button" class="btn-secondary close-modal">Cancel</button>
                        <button type="submit" class="btn-primary">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Modal for viewing an invention -->
    <div id="view-invention-modal" class="modal-overlay">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Invention Details</h2>
                <i class="fas fa-times close-modal"></i>
            </div>
            <div class="modal-body" id="view-invention-details">
                <!-- Details will be injected here by JS -->
            </div>
            <div class="form-actions" style="padding: 20px; justify-content: flex-end;">
                <button type="button" class="btn-secondary close-modal">Close</button>
            </div>
        </div>
    </div>

    <script src="inventors.js"></script>
</body>

</html>